services:
    nginx:
        image: nginx:${NGINX_VERSION}-alpine
        container_name: ${PROJECT_NAME}_nginx
        restart: always
        volumes:
            - ${PROJECT_PATH}:${SRC_PATH_CONTAINER}
            - ./etc/nginx/magento.template:/etc/nginx/conf.d/magento.template
            - ./data/certs:/etc/nginx/certs
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
            - ${NGINX_SECURE_PORT}:${NGINX_SECURE_PORT}
        command: /bin/sh -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_SECURE_PORT $$SRC_PATH_CONTAINER $$SRC_PATH_INDEX' < /etc/nginx/conf.d/magento.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        environment:
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_PORT=${NGINX_PORT}
            - NGINX_SECURE_PORT=${NGINX_SECURE_PORT}
            - SRC_PATH_CONTAINER=${SRC_PATH_CONTAINER}
            - SRC_PATH_INDEX=${SRC_PATH_INDEX}
        depends_on:
            - php
            - mysql
            - redis
            - opensearch
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.2

    php:
        build:
            context: ./images/php
            args:
                PHP_VERSION: ${PHP_VERSION}
                USER_ID: ${USER_ID}
                SRC_PATH_CONTAINER: ${SRC_PATH_CONTAINER}
                SMTP_HOST: mailhog
                SMTP_PORT: 1025
        container_name: ${PROJECT_NAME}_php
        restart: always
        volumes:
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ${PROJECT_PATH}:${SRC_PATH_CONTAINER}
            - ./scripts:/scripts
            - mage_php_webuser-data:/home/www-data # keeps track of the webuser home directory including bash history
            - ../packages:/local-packages
        environment:
            - MAGENTO_MODE=developer
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - M2_ADMIN_EMAIL=${M2_ADMIN_EMAIL}
            - M2_ADMIN_FIRSTNAME=${M2_ADMIN_FIRSTNAME}
            - M2_ADMIN_LASTNAME=${M2_ADMIN_LASTNAME}
            - M2_ADMIN_PASSWORD=${M2_ADMIN_PASSWORD}
            - M2_ADMIN_USER=${M2_ADMIN_USER}
            - M2_ADMIN_URL=${M2_ADMIN_URL}
            - M2_LANGUAGE=${M2_LANGUAGE}
            - M2_CURRENCY=${M2_CURRENCY}
            - M2_TIMEZONE=${M2_TIMEZONE}
            - M2_VERSION=${M2_VERSION}
            - NGINX_HOST=${NGINX_HOST}
            - NGINX_IP=${NGINX_IP}
            - REDIS_SESSION_HOST=redis
            - REDIS_SESSION_DATABASE_ID=0
            - REDIS_SESSION_PORT=6379
            - REDIS_SESSION_PASSWORD=magento
            - REDIS_CACHE_HOST=redis
            - REDIS_CACHE_DATABASE_ID=1
            - REDIS_CACHE_PORT=6379
            - REDIS_CACHE_PASSWORD=magento
            - REDIS_PAGE_CACHE_HOST=redis
            - REDIS_PAGE_CACHE_DATABASE_ID=2
            - REDIS_PAGE_CACHE_PORT=6379
            - REDIS_PAGE_CACHE_PASSWORD=magento
            - OPENSEARCH_HOST=opensearch
            - OPENSEARCH_PORT=9200
            - OPENSEARCH_PASSWORD=admin
        depends_on:
            - mysql
            - redis
            - mailhog
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.4

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${PROJECT_NAME}_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - NGINX_HOST=${NGINX_HOST}
        ports:
            - 8989:3306
        volumes:
            - mage_mysql-data:/var/lib/mysql
            - ./data:/data
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.5

    redis:
        image: redis:${REDIS_VERSION}-alpine
        container_name: ${PROJECT_NAME}_redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - mage_redis-data:/data
        command: redis-server --requirepass magento
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.11

    opensearch:
        image: opensearchproject/opensearch:latest
        container_name: ${PROJECT_NAME}_opensearch
        restart: always
        environment:
            - cluster.name=es-docker-cluster
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - mage_es2-data:/usr/share/opensearch/data
        ports:
            - 9201:9200
        networks:
            mageNetwork:
                  ipv4_address: 172.28.${IP_SECTION}.7

    opensearch_dashboards:
        image: opensearchproject/opensearch-dashboards:latest
        container_name: ${PROJECT_NAME}_opensearch_dashboards
        restart: always
        environment:
            - OPENSEARCH_HOSTS=http://opensearch:9200
        ports:
            - 5601:5601
        depends_on:
            - opensearch
        networks:
            mageNetwork:
                  ipv4_address: 172.28.${IP_SECTION}.12

    ## phpmyadmin will be accessible through 0.0.0.0:8081 ##
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}_phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        links:
            - mysql
        depends_on:
            - mysql
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.21
        ports:
            - "8081:80"

    mailhog:
        image: mailhog/mailhog
        container_name: ${PROJECT_NAME}_mailhog
        user: root
        restart: always
        expose:
            - 1025
            - 8025
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            mageNetwork:
                ipv4_address: 172.28.${IP_SECTION}.15


volumes:
    mage_mysql-data:
    mage_redis-data:
    mage_es-data:
    mage_es2-data:
    mage_es3-data:
    mage_php_webuser-data:

networks:
    mageNetwork:
        name: ${PROJECT_NAME}_network
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.${IP_SECTION}.0/24